ROOTPATH ?= $(shell readlink -f .)

# Optional override
-include $(ROOTPATH)/Makefile.local

KERNEL_NAME     := toulouse
KERNEL_VERSION  := 0.0.1

DEPS_DIR        := cross
DEPS_BIN_PATH   := $(ROOTPATH)/$(DEPS_DIR)/opt/cross/bin
BOOTPATH        := $(ROOTPATH)/boot
KERNELPATH      := $(ROOTPATH)/kernel
DISTPATH        := $(ROOTPATH)/dist

QEMU            ?= qemu-system-x86_64
AS              ?= as
LD              ?= ld
OBJCOPY         ?= objcopy
OBJDUMP         ?= objdump
DEBUGGER        ?= gdb
CC              := $(DEPS_BIN_PATH)/i686-elf-gcc
ELF_LD          := $(DEPS_BIN_PATH)/i686-elf-ld

ZERO_DEV        := /dev/zero

TARGET          := $(KERNEL_NAME).$(KERNEL_VERSION).img

# Shared flags
C_STRICTMODE_FLAGS := -Wall -Werror -Wextra -Wno-missing-field-initializers \
 -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition \
 -Wno-unused-parameter -Wno-unused-function -Wno-unused-value -pedantic
