ROOTPATH ?= $(shell readlink -f .)

# Optional override
-include $(ROOTPATH)/Makefile.local

KERNEL_NAME			:= toulouse
KERNEL_VERSION 	:= 0.0.1

DEPS_DIR 				:= deps
DEPS_BIN_PATH 	:= ./$(DEPS_DIR)/opt/cross/bin/
BOOTPATH        := $(ROOTPATH)/boot
DISTPATH        := $(ROOTPATH)/dist

QEMU 			?= qemu-system-x86_64
AS	 			?= as
LD 				?= ld
OBJCOPY 	?= objcopy
OBJDUMP 	?= objdump
CC 				:= gcc
ELF_LD 		:= $(DEPS_BIN_PATH)/i686-elf-ld

ZERO_DEV 	:= /dev/zero

TARGET    := $(KERNEL_NAME).$(KERNEL_VERSION).img
